### ISSUE TITLE
Search of users not working

### ISSUE THREAD

**Issue by jhsu802701** [jhsu802701/rails_neutrino_5#16]
Fix the search and provide integration tests

**Comment by jhsu802701** [comment]
* Add kaminari to the Gemfile
* config/locales/en.yml: add
```
  views:
    pagination:
      previous: "&lt; Previous"
      next: "Next &gt;"
      truncate: "..."
```
* config/routes.rb: make "resources :user" portion
```
  resources :users, except: [:new, :create, :edit, :update] do
    root :to => "users#index"
    collection { post :search, to: 'users#index' }
  end
```
* app/views/users/index.html.erb: "<%= paginate @users %>" instead of will_paginate
